import os
import csv
print("Election Results")
print()
print("---------------------------")
print()
print("total Votes:")
print()
print("---------------------------")
print()
print("Charles Casper Stockham:")
print("Diana DeGette:")
print("Anthony Doane:")
print()
print("---------------------------")
print()
print("Winner:")
print()
print("---------------------------")
